name: neerutils
description: A collection of Utility functions in dart.
version: 0.1.1
homepage: https://neerajjaiswal.com
repository: https://github.com/neerajjaiswal/neerutils
issue_tracker: https://github.com/neerajjaiswal/neerutils/issues
email: neeraj.jaiswal@gmail.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
#  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
